spring:
  application:
    name: alphary-backend
  r2dbc:
    url: ${R2DBC_URL:r2dbc:postgresql://localhost:5432/dev_db}
    username: ${DB_USERNAME:dev_user}
    password: ${DB_PASSWORD:dev_password}
  datasource:
    url: ${JDBC_URL:jdbc:postgresql://localhost:5432/dev_db}
    username: ${DB_USERNAME:dev_user}
    password: ${DB_PASSWORD:dev_password}
    driver-class-name: org.postgresql.Driver
  graphql:
    path: "/graphql"
  liquibase:
    enabled: true
    change-log: classpath:db/changelog/db.changelog-master.xml
    url: ${JDBC_URL:jdbc:postgresql://localhost:5432/dev_db}
    user: ${DB_USERNAME:dev_user}
    password: ${DB_PASSWORD:dev_password}